refactor: throw preprocessor errors instead of writing disclaimers this just means gcc will throw an error instead of just returning undefined reference to 'x' when running/compiling non-embedded code from embedded mode.